export enum NODES {
  LINKING_RESOURCE = 'node:linking_resource',
  ASSEMBLY_CONTEXT = 'node:assembly_context',
  RESOURCE_CONTAINER = 'node:resource_container',
  SYSTEM = 'node:system',
  START = 'node:start',
  STOP = 'node:stop',
  USAGE_SCENARIO = 'node:usage_scenatio',
  SCENARIO_BEHAVIOUR = 'node:scenario_behaviour',
  INTERFACE = 'node:interface',
  COMPOSITE_DATA_TYPE = 'node:composite_data_type',
  BASIC_COMPONENT = 'node:basic_component',
  ENTRY_LEVEL_SYSTEM_CALL = 'node:entry_level_system_call',
  UNCONCRETE_ACTION = 'node:unconcrete_action',
  SEFF_SIGNATURE_LABEL = 'label:seff_signature',
  SET_VARIABLE = 'node:set_variable',
  BRANCH = 'node:branch',
  PROBABILISTIC_BRANCH_TRANSITION = 'node:probabilistic_branch_transition',
  GUARDED_BRANCH_TRANSITION = 'node:guarded_branch_transition',
  BRANCH_TRANSTION = 'node:branch_transition',
}